/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SacolaRouteImport } from './routes/sacola'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaContaIndexRouteImport } from './routes/minha-conta.index'
import { Route as AtacadoIndexRouteImport } from './routes/atacado.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as MinhaContaPedidosRouteImport } from './routes/minha-conta.pedidos'
import { Route as MinhaContaFavoritosRouteImport } from './routes/minha-conta.favoritos'
import { Route as MinhaContaEnderecosRouteImport } from './routes/minha-conta.enderecos'
import { Route as MinhaContaDadosRouteImport } from './routes/minha-conta.dados'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AtacadoHomeRouteImport } from './routes/atacado.home'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWholesaleApplicationsRouteImport } from './routes/_authenticated/admin.wholesale-applications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin.suppliers'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin.stores'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPurchasesRouteImport } from './routes/_authenticated/admin.purchases'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPriceListsRouteImport } from './routes/_authenticated/admin.price-lists'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin.marketing'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminDamRouteImport } from './routes/_authenticated/admin.dam'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCustomerGroupsRouteImport } from './routes/_authenticated/admin.customer-groups'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminCollectionsRouteImport } from './routes/_authenticated/admin.collections'
import { Route as AuthenticatedAdminCategoryAttributesRouteImport } from './routes/_authenticated/admin.category-attributes'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCatalogAuditRouteImport } from './routes/_authenticated/admin.catalog-audit'
import { Route as AuthenticatedAdminCartsRouteImport } from './routes/_authenticated/admin.carts'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAttributesRouteImport } from './routes/_authenticated/admin.attributes'
import { Route as AuthenticatedAdminAttributeValuesRouteImport } from './routes/_authenticated/admin.attribute-values'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as ApiPublicHooksShippingTrackingSyncRouteImport } from './routes/api/public/hooks/shipping-tracking-sync'
import { Route as ApiPublicHooksNuvemfiscalRouteImport } from './routes/api/public/hooks/nuvemfiscal'
import { Route as ApiPublicHooksMercadopagoRouteImport } from './routes/api/public/hooks/mercadopago'
import { Route as ApiPublicHooksMelhorEnvioWebhookRouteImport } from './routes/api/public/hooks/melhor-envio-webhook'
import { Route as ApiPublicHooksMelhorEnvioCallbackRouteImport } from './routes/api/public/hooks/melhor-envio-callback'
import { Route as AuthenticatedAdminPurchasesPoIdRouteImport } from './routes/_authenticated/admin.purchases.$poId'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin.products.new'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin.orders.$orderId'
import { Route as AuthenticatedAdminInvoicesInvoiceIdRouteImport } from './routes/_authenticated/admin.invoices.$invoiceId'
import { Route as AuthenticatedAdminInventoryStockLevelIdRouteImport } from './routes/_authenticated/admin.inventory.$stockLevelId'
import { Route as AuthenticatedAdminCustomersCustomerIdRouteImport } from './routes/_authenticated/admin.customers.$customerId'
import { Route as AuthenticatedAdminProductsIdEditRouteImport } from './routes/_authenticated/admin.products.$id.edit'

const SacolaRoute = SacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaIndexRoute = MinhaContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const AtacadoIndexRoute = AtacadoIndexRouteImport.update({
  id: '/atacado/',
  path: '/atacado/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPedidosRoute = MinhaContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaFavoritosRoute = MinhaContaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaEnderecosRoute = MinhaContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaDadosRoute = MinhaContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => MinhaContaRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtacadoHomeRoute = AtacadoHomeRouteImport.update({
  id: '/atacado/home',
  path: '/atacado/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWholesaleApplicationsRoute =
  AuthenticatedAdminWholesaleApplicationsRouteImport.update({
    id: '/wholesale-applications',
    path: '/wholesale-applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPurchasesRoute =
  AuthenticatedAdminPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPriceListsRoute =
  AuthenticatedAdminPriceListsRouteImport.update({
    id: '/price-lists',
    path: '/price-lists',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDamRoute = AuthenticatedAdminDamRouteImport.update({
  id: '/dam',
  path: '/dam',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomerGroupsRoute =
  AuthenticatedAdminCustomerGroupsRouteImport.update({
    id: '/customer-groups',
    path: '/customer-groups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCollectionsRoute =
  AuthenticatedAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoryAttributesRoute =
  AuthenticatedAdminCategoryAttributesRouteImport.update({
    id: '/category-attributes',
    path: '/category-attributes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogAuditRoute =
  AuthenticatedAdminCatalogAuditRouteImport.update({
    id: '/catalog-audit',
    path: '/catalog-audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCartsRoute = AuthenticatedAdminCartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttributesRoute =
  AuthenticatedAdminAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttributeValuesRoute =
  AuthenticatedAdminAttributeValuesRouteImport.update({
    id: '/attribute-values',
    path: '/attribute-values',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const ApiPublicHooksShippingTrackingSyncRoute =
  ApiPublicHooksShippingTrackingSyncRouteImport.update({
    id: '/api/public/hooks/shipping-tracking-sync',
    path: '/api/public/hooks/shipping-tracking-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNuvemfiscalRoute =
  ApiPublicHooksNuvemfiscalRouteImport.update({
    id: '/api/public/hooks/nuvemfiscal',
    path: '/api/public/hooks/nuvemfiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMercadopagoRoute =
  ApiPublicHooksMercadopagoRouteImport.update({
    id: '/api/public/hooks/mercadopago',
    path: '/api/public/hooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMelhorEnvioWebhookRoute =
  ApiPublicHooksMelhorEnvioWebhookRouteImport.update({
    id: '/api/public/hooks/melhor-envio-webhook',
    path: '/api/public/hooks/melhor-envio-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMelhorEnvioCallbackRoute =
  ApiPublicHooksMelhorEnvioCallbackRouteImport.update({
    id: '/api/public/hooks/melhor-envio-callback',
    path: '/api/public/hooks/melhor-envio-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPurchasesPoIdRoute =
  AuthenticatedAdminPurchasesPoIdRouteImport.update({
    id: '/$poId',
    path: '/$poId',
    getParentRoute: () => AuthenticatedAdminPurchasesRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminInvoicesInvoiceIdRoute =
  AuthenticatedAdminInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedAdminInvoicesRoute,
  } as any)
const AuthenticatedAdminInventoryStockLevelIdRoute =
  AuthenticatedAdminInventoryStockLevelIdRouteImport.update({
    id: '/$stockLevelId',
    path: '/$stockLevelId',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminCustomersCustomerIdRoute =
  AuthenticatedAdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminProductsIdEditRoute =
  AuthenticatedAdminProductsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/atacado/home': typeof AtacadoHomeRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/favoritos': typeof MinhaContaFavoritosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/atacado/': typeof AtacadoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/attribute-values': typeof AuthenticatedAdminAttributeValuesRoute
  '/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/admin/catalog-audit': typeof AuthenticatedAdminCatalogAuditRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/category-attributes': typeof AuthenticatedAdminCategoryAttributesRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customer-groups': typeof AuthenticatedAdminCustomerGroupsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dam': typeof AuthenticatedAdminDamRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wholesale-applications': typeof AuthenticatedAdminWholesaleApplicationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$customerId': typeof AuthenticatedAdminCustomersCustomerIdRoute
  '/admin/inventory/$stockLevelId': typeof AuthenticatedAdminInventoryStockLevelIdRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/purchases/$poId': typeof AuthenticatedAdminPurchasesPoIdRoute
  '/api/public/hooks/melhor-envio-callback': typeof ApiPublicHooksMelhorEnvioCallbackRoute
  '/api/public/hooks/melhor-envio-webhook': typeof ApiPublicHooksMelhorEnvioWebhookRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/nuvemfiscal': typeof ApiPublicHooksNuvemfiscalRoute
  '/api/public/hooks/shipping-tracking-sync': typeof ApiPublicHooksShippingTrackingSyncRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/products/$id/edit': typeof AuthenticatedAdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/atacado/home': typeof AtacadoHomeRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/favoritos': typeof MinhaContaFavoritosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/atacado': typeof AtacadoIndexRoute
  '/minha-conta': typeof MinhaContaIndexRoute
  '/admin/attribute-values': typeof AuthenticatedAdminAttributeValuesRoute
  '/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/admin/catalog-audit': typeof AuthenticatedAdminCatalogAuditRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/category-attributes': typeof AuthenticatedAdminCategoryAttributesRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customer-groups': typeof AuthenticatedAdminCustomerGroupsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dam': typeof AuthenticatedAdminDamRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wholesale-applications': typeof AuthenticatedAdminWholesaleApplicationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$customerId': typeof AuthenticatedAdminCustomersCustomerIdRoute
  '/admin/inventory/$stockLevelId': typeof AuthenticatedAdminInventoryStockLevelIdRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/purchases/$poId': typeof AuthenticatedAdminPurchasesPoIdRoute
  '/api/public/hooks/melhor-envio-callback': typeof ApiPublicHooksMelhorEnvioCallbackRoute
  '/api/public/hooks/melhor-envio-webhook': typeof ApiPublicHooksMelhorEnvioWebhookRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/nuvemfiscal': typeof ApiPublicHooksNuvemfiscalRoute
  '/api/public/hooks/shipping-tracking-sync': typeof ApiPublicHooksShippingTrackingSyncRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/products/$id/edit': typeof AuthenticatedAdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/atacado/home': typeof AtacadoHomeRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/favoritos': typeof MinhaContaFavoritosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/atacado/': typeof AtacadoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/_authenticated/admin/attribute-values': typeof AuthenticatedAdminAttributeValuesRoute
  '/_authenticated/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/_authenticated/admin/catalog-audit': typeof AuthenticatedAdminCatalogAuditRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/category-attributes': typeof AuthenticatedAdminCategoryAttributesRoute
  '/_authenticated/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customer-groups': typeof AuthenticatedAdminCustomerGroupsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/dam': typeof AuthenticatedAdminDamRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/wholesale-applications': typeof AuthenticatedAdminWholesaleApplicationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers/$customerId': typeof AuthenticatedAdminCustomersCustomerIdRoute
  '/_authenticated/admin/inventory/$stockLevelId': typeof AuthenticatedAdminInventoryStockLevelIdRoute
  '/_authenticated/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/_authenticated/admin/purchases/$poId': typeof AuthenticatedAdminPurchasesPoIdRoute
  '/api/public/hooks/melhor-envio-callback': typeof ApiPublicHooksMelhorEnvioCallbackRoute
  '/api/public/hooks/melhor-envio-webhook': typeof ApiPublicHooksMelhorEnvioWebhookRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/nuvemfiscal': typeof ApiPublicHooksNuvemfiscalRoute
  '/api/public/hooks/shipping-tracking-sync': typeof ApiPublicHooksShippingTrackingSyncRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/products/$id/edit': typeof AuthenticatedAdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/minha-conta'
    | '/produtos'
    | '/reset-password'
    | '/sacola'
    | '/admin'
    | '/atacado/home'
    | '/categoria/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/enderecos'
    | '/minha-conta/favoritos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/atacado/'
    | '/minha-conta/'
    | '/admin/attribute-values'
    | '/admin/attributes'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/carts'
    | '/admin/catalog-audit'
    | '/admin/categories'
    | '/admin/category-attributes'
    | '/admin/collections'
    | '/admin/companies'
    | '/admin/coupons'
    | '/admin/customer-groups'
    | '/admin/customers'
    | '/admin/dam'
    | '/admin/employees'
    | '/admin/integracoes'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/logs'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/price-lists'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/wholesale-applications'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/inventory/$stockLevelId'
    | '/admin/invoices/$invoiceId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/admin/purchases/$poId'
    | '/api/public/hooks/melhor-envio-callback'
    | '/api/public/hooks/melhor-envio-webhook'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/nuvemfiscal'
    | '/api/public/hooks/shipping-tracking-sync'
    | '/admin/products/'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/produtos'
    | '/reset-password'
    | '/sacola'
    | '/atacado/home'
    | '/categoria/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/enderecos'
    | '/minha-conta/favoritos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/atacado'
    | '/minha-conta'
    | '/admin/attribute-values'
    | '/admin/attributes'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/carts'
    | '/admin/catalog-audit'
    | '/admin/categories'
    | '/admin/category-attributes'
    | '/admin/collections'
    | '/admin/companies'
    | '/admin/coupons'
    | '/admin/customer-groups'
    | '/admin/customers'
    | '/admin/dam'
    | '/admin/employees'
    | '/admin/integracoes'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/logs'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/price-lists'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/wholesale-applications'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/inventory/$stockLevelId'
    | '/admin/invoices/$invoiceId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/admin/purchases/$poId'
    | '/api/public/hooks/melhor-envio-callback'
    | '/api/public/hooks/melhor-envio-webhook'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/nuvemfiscal'
    | '/api/public/hooks/shipping-tracking-sync'
    | '/admin/products'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/minha-conta'
    | '/produtos'
    | '/reset-password'
    | '/sacola'
    | '/_authenticated/admin'
    | '/atacado/home'
    | '/categoria/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/enderecos'
    | '/minha-conta/favoritos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/atacado/'
    | '/minha-conta/'
    | '/_authenticated/admin/attribute-values'
    | '/_authenticated/admin/attributes'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/carts'
    | '/_authenticated/admin/catalog-audit'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/category-attributes'
    | '/_authenticated/admin/collections'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customer-groups'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dam'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/price-lists'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/purchases'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/wholesale-applications'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers/$customerId'
    | '/_authenticated/admin/inventory/$stockLevelId'
    | '/_authenticated/admin/invoices/$invoiceId'
    | '/_authenticated/admin/orders/$orderId'
    | '/_authenticated/admin/products/new'
    | '/_authenticated/admin/purchases/$poId'
    | '/api/public/hooks/melhor-envio-callback'
    | '/api/public/hooks/melhor-envio-webhook'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/nuvemfiscal'
    | '/api/public/hooks/shipping-tracking-sync'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SacolaRoute: typeof SacolaRoute
  AtacadoHomeRoute: typeof AtacadoHomeRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AtacadoIndexRoute: typeof AtacadoIndexRoute
  ApiPublicHooksMelhorEnvioCallbackRoute: typeof ApiPublicHooksMelhorEnvioCallbackRoute
  ApiPublicHooksMelhorEnvioWebhookRoute: typeof ApiPublicHooksMelhorEnvioWebhookRoute
  ApiPublicHooksMercadopagoRoute: typeof ApiPublicHooksMercadopagoRoute
  ApiPublicHooksNuvemfiscalRoute: typeof ApiPublicHooksNuvemfiscalRoute
  ApiPublicHooksShippingTrackingSyncRoute: typeof ApiPublicHooksShippingTrackingSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sacola': {
      id: '/sacola'
      path: '/sacola'
      fullPath: '/sacola'
      preLoaderRoute: typeof SacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/': {
      id: '/minha-conta/'
      path: '/'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof MinhaContaIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/atacado/': {
      id: '/atacado/'
      path: '/atacado'
      fullPath: '/atacado/'
      preLoaderRoute: typeof AtacadoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/pedidos': {
      id: '/minha-conta/pedidos'
      path: '/pedidos'
      fullPath: '/minha-conta/pedidos'
      preLoaderRoute: typeof MinhaContaPedidosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/favoritos': {
      id: '/minha-conta/favoritos'
      path: '/favoritos'
      fullPath: '/minha-conta/favoritos'
      preLoaderRoute: typeof MinhaContaFavoritosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/enderecos': {
      id: '/minha-conta/enderecos'
      path: '/enderecos'
      fullPath: '/minha-conta/enderecos'
      preLoaderRoute: typeof MinhaContaEnderecosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/dados': {
      id: '/minha-conta/dados'
      path: '/dados'
      fullPath: '/minha-conta/dados'
      preLoaderRoute: typeof MinhaContaDadosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atacado/home': {
      id: '/atacado/home'
      path: '/atacado/home'
      fullPath: '/atacado/home'
      preLoaderRoute: typeof AtacadoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wholesale-applications': {
      id: '/_authenticated/admin/wholesale-applications'
      path: '/wholesale-applications'
      fullPath: '/admin/wholesale-applications'
      preLoaderRoute: typeof AuthenticatedAdminWholesaleApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/purchases': {
      id: '/_authenticated/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/price-lists': {
      id: '/_authenticated/admin/price-lists'
      path: '/price-lists'
      fullPath: '/admin/price-lists'
      preLoaderRoute: typeof AuthenticatedAdminPriceListsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dam': {
      id: '/_authenticated/admin/dam'
      path: '/dam'
      fullPath: '/admin/dam'
      preLoaderRoute: typeof AuthenticatedAdminDamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customer-groups': {
      id: '/_authenticated/admin/customer-groups'
      path: '/customer-groups'
      fullPath: '/admin/customer-groups'
      preLoaderRoute: typeof AuthenticatedAdminCustomerGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/collections': {
      id: '/_authenticated/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/category-attributes': {
      id: '/_authenticated/admin/category-attributes'
      path: '/category-attributes'
      fullPath: '/admin/category-attributes'
      preLoaderRoute: typeof AuthenticatedAdminCategoryAttributesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog-audit': {
      id: '/_authenticated/admin/catalog-audit'
      path: '/catalog-audit'
      fullPath: '/admin/catalog-audit'
      preLoaderRoute: typeof AuthenticatedAdminCatalogAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carts': {
      id: '/_authenticated/admin/carts'
      path: '/carts'
      fullPath: '/admin/carts'
      preLoaderRoute: typeof AuthenticatedAdminCartsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attributes': {
      id: '/_authenticated/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AuthenticatedAdminAttributesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attribute-values': {
      id: '/_authenticated/admin/attribute-values'
      path: '/attribute-values'
      fullPath: '/admin/attribute-values'
      preLoaderRoute: typeof AuthenticatedAdminAttributeValuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/api/public/hooks/shipping-tracking-sync': {
      id: '/api/public/hooks/shipping-tracking-sync'
      path: '/api/public/hooks/shipping-tracking-sync'
      fullPath: '/api/public/hooks/shipping-tracking-sync'
      preLoaderRoute: typeof ApiPublicHooksShippingTrackingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nuvemfiscal': {
      id: '/api/public/hooks/nuvemfiscal'
      path: '/api/public/hooks/nuvemfiscal'
      fullPath: '/api/public/hooks/nuvemfiscal'
      preLoaderRoute: typeof ApiPublicHooksNuvemfiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mercadopago': {
      id: '/api/public/hooks/mercadopago'
      path: '/api/public/hooks/mercadopago'
      fullPath: '/api/public/hooks/mercadopago'
      preLoaderRoute: typeof ApiPublicHooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/melhor-envio-webhook': {
      id: '/api/public/hooks/melhor-envio-webhook'
      path: '/api/public/hooks/melhor-envio-webhook'
      fullPath: '/api/public/hooks/melhor-envio-webhook'
      preLoaderRoute: typeof ApiPublicHooksMelhorEnvioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/melhor-envio-callback': {
      id: '/api/public/hooks/melhor-envio-callback'
      path: '/api/public/hooks/melhor-envio-callback'
      fullPath: '/api/public/hooks/melhor-envio-callback'
      preLoaderRoute: typeof ApiPublicHooksMelhorEnvioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/purchases/$poId': {
      id: '/_authenticated/admin/purchases/$poId'
      path: '/$poId'
      fullPath: '/admin/purchases/$poId'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesPoIdRouteImport
      parentRoute: typeof AuthenticatedAdminPurchasesRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/invoices/$invoiceId': {
      id: '/_authenticated/admin/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedAdminInvoicesRoute
    }
    '/_authenticated/admin/inventory/$stockLevelId': {
      id: '/_authenticated/admin/inventory/$stockLevelId'
      path: '/$stockLevelId'
      fullPath: '/admin/inventory/$stockLevelId'
      preLoaderRoute: typeof AuthenticatedAdminInventoryStockLevelIdRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/customers/$customerId': {
      id: '/_authenticated/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedAdminCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/products/$id/edit': {
      id: '/_authenticated/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersCustomerIdRoute: typeof AuthenticatedAdminCustomersCustomerIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersCustomerIdRoute:
      AuthenticatedAdminCustomersCustomerIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminInventoryRouteChildren {
  AuthenticatedAdminInventoryStockLevelIdRoute: typeof AuthenticatedAdminInventoryStockLevelIdRoute
}

const AuthenticatedAdminInventoryRouteChildren: AuthenticatedAdminInventoryRouteChildren =
  {
    AuthenticatedAdminInventoryStockLevelIdRoute:
      AuthenticatedAdminInventoryStockLevelIdRoute,
  }

const AuthenticatedAdminInventoryRouteWithChildren =
  AuthenticatedAdminInventoryRoute._addFileChildren(
    AuthenticatedAdminInventoryRouteChildren,
  )

interface AuthenticatedAdminInvoicesRouteChildren {
  AuthenticatedAdminInvoicesInvoiceIdRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRoute
}

const AuthenticatedAdminInvoicesRouteChildren: AuthenticatedAdminInvoicesRouteChildren =
  {
    AuthenticatedAdminInvoicesInvoiceIdRoute:
      AuthenticatedAdminInvoicesInvoiceIdRoute,
  }

const AuthenticatedAdminInvoicesRouteWithChildren =
  AuthenticatedAdminInvoicesRoute._addFileChildren(
    AuthenticatedAdminInvoicesRouteChildren,
  )

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminProductsIdEditRoute: typeof AuthenticatedAdminProductsIdEditRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminProductsIdEditRoute:
      AuthenticatedAdminProductsIdEditRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminPurchasesRouteChildren {
  AuthenticatedAdminPurchasesPoIdRoute: typeof AuthenticatedAdminPurchasesPoIdRoute
}

const AuthenticatedAdminPurchasesRouteChildren: AuthenticatedAdminPurchasesRouteChildren =
  {
    AuthenticatedAdminPurchasesPoIdRoute: AuthenticatedAdminPurchasesPoIdRoute,
  }

const AuthenticatedAdminPurchasesRouteWithChildren =
  AuthenticatedAdminPurchasesRoute._addFileChildren(
    AuthenticatedAdminPurchasesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttributeValuesRoute: typeof AuthenticatedAdminAttributeValuesRoute
  AuthenticatedAdminAttributesRoute: typeof AuthenticatedAdminAttributesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCartsRoute: typeof AuthenticatedAdminCartsRoute
  AuthenticatedAdminCatalogAuditRoute: typeof AuthenticatedAdminCatalogAuditRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCategoryAttributesRoute: typeof AuthenticatedAdminCategoryAttributesRoute
  AuthenticatedAdminCollectionsRoute: typeof AuthenticatedAdminCollectionsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomerGroupsRoute: typeof AuthenticatedAdminCustomerGroupsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDamRoute: typeof AuthenticatedAdminDamRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRouteWithChildren
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRouteWithChildren
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPriceListsRoute: typeof AuthenticatedAdminPriceListsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminPurchasesRoute: typeof AuthenticatedAdminPurchasesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWholesaleApplicationsRoute: typeof AuthenticatedAdminWholesaleApplicationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttributeValuesRoute:
    AuthenticatedAdminAttributeValuesRoute,
  AuthenticatedAdminAttributesRoute: AuthenticatedAdminAttributesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminCartsRoute: AuthenticatedAdminCartsRoute,
  AuthenticatedAdminCatalogAuditRoute: AuthenticatedAdminCatalogAuditRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCategoryAttributesRoute:
    AuthenticatedAdminCategoryAttributesRoute,
  AuthenticatedAdminCollectionsRoute: AuthenticatedAdminCollectionsRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomerGroupsRoute: AuthenticatedAdminCustomerGroupsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDamRoute: AuthenticatedAdminDamRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminInventoryRoute:
    AuthenticatedAdminInventoryRouteWithChildren,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRouteWithChildren,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPriceListsRoute: AuthenticatedAdminPriceListsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRouteWithChildren,
  AuthenticatedAdminPurchasesRoute:
    AuthenticatedAdminPurchasesRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWholesaleApplicationsRoute:
    AuthenticatedAdminWholesaleApplicationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaDadosRoute: typeof MinhaContaDadosRoute
  MinhaContaEnderecosRoute: typeof MinhaContaEnderecosRoute
  MinhaContaFavoritosRoute: typeof MinhaContaFavoritosRoute
  MinhaContaPedidosRoute: typeof MinhaContaPedidosRoute
  MinhaContaIndexRoute: typeof MinhaContaIndexRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaDadosRoute: MinhaContaDadosRoute,
  MinhaContaEnderecosRoute: MinhaContaEnderecosRoute,
  MinhaContaFavoritosRoute: MinhaContaFavoritosRoute,
  MinhaContaPedidosRoute: MinhaContaPedidosRoute,
  MinhaContaIndexRoute: MinhaContaIndexRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SacolaRoute: SacolaRoute,
  AtacadoHomeRoute: AtacadoHomeRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AtacadoIndexRoute: AtacadoIndexRoute,
  ApiPublicHooksMelhorEnvioCallbackRoute:
    ApiPublicHooksMelhorEnvioCallbackRoute,
  ApiPublicHooksMelhorEnvioWebhookRoute: ApiPublicHooksMelhorEnvioWebhookRoute,
  ApiPublicHooksMercadopagoRoute: ApiPublicHooksMercadopagoRoute,
  ApiPublicHooksNuvemfiscalRoute: ApiPublicHooksNuvemfiscalRoute,
  ApiPublicHooksShippingTrackingSyncRoute:
    ApiPublicHooksShippingTrackingSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
