// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrysjmmxgcofwmhmushj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyeXNqbW14Z2NvZndtaG11c2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5Nzk2MDgsImV4cCI6MjA5NzU1NTYwOH0.K1v__GwXarlKfZvBf1u_Y9eaGkNd0p28rwoQkVJEvXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});